<script setup lang="ts">
import { courses, levelNames } from '~/data/courses'
import { courseSlug } from '~/utils/course-route'
const route = useRoute(); const { loadUser } = useAuth(); const fallback = courses.find(item => courseSlug(item.title) === route.params.slug) || courses[0]; const course = ref<any>(fallback); const databaseCourse = ref<any>(null)
const sections = [['Variable', 'Variable adalah tempat menyimpan nilai supaya bisa dipakai ulang di bagian lain program.', 'const namaPengguna = "Ilan";\nlet jumlahPoin = 10;\njumlahPoin += 5;\nconsole.log(jumlahPoin);'], ['Aritmatika & Operator', 'Operator aritmatika dipakai untuk melakukan perhitungan matematis.', 'const a = 10;\nconst b = 3;\nconsole.log(a + b);'], ['Array', 'Array menyimpan kumpulan nilai dalam satu variable.', 'const bahasaPemrograman = ["JavaScript", "Python", "Go"];\nconsole.log(bahasaPemrograman);'], ['Object', 'Object menyimpan data dalam pasangan key dan value.', 'const course = { judul: "JavaScript" };\nconsole.log(course.judul);'], ['Function', 'Function membungkus logika yang dapat dipanggil berulang kali.', 'function hitungTotal(harga, jumlah) { return harga * jumlah; }\nconsole.log(hitungTotal(50000, 3));']]
useHead(() => ({ title: `${course.value.title} - Coding Camp RPL 2026` }))
onMounted(async () => { if (!await loadUser()) return navigateTo({ path: '/login', query: { redirect: route.fullPath } }); try { databaseCourse.value = (await $fetch<{ course: any }>(`/api/courses/${route.query.id}`)).course; course.value = databaseCourse.value } catch { await navigateTo('/') } })
</script>
<template><SiteNav /><main><section class="article-hero"><div class="container"><div class="article-meta-row"><span class="article-category">{{ course.category }}</span><span class="article-duration">◷ {{ course.duration }}</span><span class="article-level">{{ levelNames[course.level] }}</span></div><h1 class="article-title">{{ course.title }}</h1><p class="article-description">{{ course.description }}</p></div></section><section class="article-body"><div class="container"><article class="article-content"><RichTextReader v-if="databaseCourse?.content" :content="databaseCourse.content" /><template v-else><div v-for="(section, index) in sections" :key="section[0]" class="content-section"><p class="section-number">{{ String(index + 1).padStart(2, '0') }}</p><h2 class="content-heading">{{ section[0] }}</h2><p class="content-paragraph">{{ section[1] }}</p><CodePlayground :code="section[2]" :filename="`${courseSlug(section[0])}.js`" /></div></template><div class="article-nav-footer"><NuxtLink to="/#course">&lt;- Kembali ke Course</NuxtLink></div></article></div></section></main><SiteFooter /></template>
