<script setup lang="ts">
definePageMeta({ layout: 'dashboard' })
type Course = { id: string; title: string; description: string; learning_objectives: string; content: Record<string, unknown> | null; image: string; level: string; category: string; duration: string; uploaded_at: string }
const { user, loadUser } = useAuth(); const courses = ref<Course[]>([]); const loading = ref(true); const errorMessage = ref(''); const editing = ref<Course | null>(null)
const emptyContent = () => ({ type: 'doc', content: [{ type: 'paragraph' }] })
const form = reactive({ title: '', description: '', learningObjectives: '', content: emptyContent(), image: '', level: 'beginner', category: '', duration: '', uploadedAt: new Date().toISOString().slice(0, 10) })
async function loadCourses() { if (!await loadUser()) return navigateTo({ path: '/login', query: { redirect: '/admin/courses' } }); if (user.value?.role !== 'admin') return navigateTo('/dashboard'); courses.value = (await $fetch<{ courses: Course[] }>('/api/admin/courses')).courses; loading.value = false }
function editCourse(item: Course) { editing.value = item; Object.assign(form, { title: item.title, description: item.description, learningObjectives: item.learning_objectives, content: item.content || emptyContent(), image: item.image, level: item.level, category: item.category, duration: item.duration, uploadedAt: item.uploaded_at }) }
function resetForm() { editing.value = null; Object.assign(form, { title: '', description: '', learningObjectives: '', content: emptyContent(), image: '', level: 'beginner', category: '', duration: '', uploadedAt: new Date().toISOString().slice(0, 10) }) }
async function saveCourse() { errorMessage.value = ''; try { if (editing.value) await $fetch(`/api/admin/courses/${editing.value.id}`, { method: 'PUT', body: form }); else await $fetch('/api/admin/courses', { method: 'POST', body: form }); resetForm(); await loadCourses() } catch (error: any) { errorMessage.value = error.data?.statusMessage || error.data?.message || 'Course gagal disimpan' } }
async function deleteCourse(id: string) { await $fetch(`/api/admin/courses/${id}`, { method: 'DELETE' }); await loadCourses() }
onMounted(loadCourses)
</script>
<template>
  <UDashboardPanel id="admin-courses"><template #header><UDashboardNavbar title="Course"><template #leading><UDashboardSidebarCollapse /></template><template #right><UButton label="Course Baru" icon="i-lucide-plus" color="primary" @click="resetForm" /></template></UDashboardNavbar><UDashboardToolbar><template #left><span class="text-sm text-muted">Buat, edit, dan susun materi course</span></template></UDashboardToolbar></template><template #body><div v-if="loading" class="p-8 text-muted">Memuat courses...</div><div v-else class="space-y-6"><p v-if="errorMessage" class="text-error">{{ errorMessage }}</p><UPageCard title="Course Editor" description="Metadata course dan materi rich text." icon="i-lucide-pencil"><form class="grid gap-3 md:grid-cols-3" @submit.prevent="saveCourse"><UInput v-model="form.title" placeholder="Judul course" required /><UInput v-model="form.category" placeholder="Kategori" required /><UInput v-model="form.duration" placeholder="Durasi" required /><UInput v-model="form.image" placeholder="URL cover image" required /><USelect v-model="form.level" :items="[{ label: 'Dasar', value: 'beginner' }, { label: 'Menengah', value: 'intermediate' }, { label: 'Sulit', value: 'advanced' }]" value-key="value" /><UInput v-model="form.uploadedAt" type="date" required /><UTextarea v-model="form.description" class="md:col-span-3" placeholder="Deskripsi" required /><UTextarea v-model="form.learningObjectives" class="md:col-span-3" placeholder="Tujuan pembelajaran" required /><div class="md:col-span-3"><p class="mb-2 text-sm font-medium">Materi Course</p><RichTextEditor v-model="form.content" /></div><div class="flex gap-2 md:col-span-3"><UButton type="submit" :label="editing ? 'Simpan Perubahan' : 'Tambah Course'" color="primary" /><UButton v-if="editing" label="Batal" color="neutral" variant="outline" type="button" @click="resetForm" /></div></form></UPageCard><UPageCard title="Daftar Course" :description="`${courses.length} course tersedia`" icon="i-lucide-book-open"><div class="grid gap-3"><div v-for="item in courses" :key="item.id" class="flex items-center justify-between gap-4 rounded-lg border border-default p-4"><div><strong class="text-highlighted">{{ item.title }}</strong><p class="text-sm text-muted">{{ item.category }} · {{ item.level }}</p></div><div class="flex gap-2"><UButton label="Edit" color="primary" variant="ghost" @click="editCourse(item)" /><UButton label="Hapus" color="error" variant="ghost" @click="deleteCourse(item.id)" /></div></div></div></UPageCard></div></template></UDashboardPanel>
</template>
