<script setup lang="ts">
type Quiz = { question: string; options: string[]; correctIndex: number; explanation: string }
const props = defineProps<{ modelValue?: Quiz }>()
const emit = defineEmits<{ save: [quiz: Quiz]; cancel: [] }>()
const question = ref(props.modelValue?.question || '')
const options = ref([...(props.modelValue?.options || ['', '', '', '']), '', '', ''].slice(0, 4))
const correctIndex = ref(props.modelValue?.correctIndex || 0)
const explanation = ref(props.modelValue?.explanation || '')
const points = ref(1)
const time = ref(30)
const multiple = ref(false)
const preview = ref(false)
const answered = ref<number | null>(null)
function save() { const validOptions = options.value.filter(option => option.trim()); if (!question.value.trim() || validOptions.length < 2) return; emit('save', { question: question.value.trim(), options: validOptions, correctIndex: Math.min(correctIndex.value, validOptions.length - 1), explanation: explanation.value.trim() }) }
</script>
<template>
  <div class="quizground-editor"><header class="quizground-toolbar"><UButton icon="i-lucide-arrow-left" color="neutral" variant="ghost" aria-label="Kembali" @click="emit('cancel')" /><USelect v-model="time" :items="[15, 30, 60, 90].map(value => ({ label: `${value} seconds`, value }))" value-key="value" /><USelect v-model="points" :items="[1, 2, 3, 5].map(value => ({ label: `${value} point`, value }))" value-key="value" /><UButton :label="preview ? 'Edit question' : 'Preview question'" :icon="preview ? 'i-lucide-pencil' : 'i-lucide-eye'" color="neutral" variant="outline" @click="preview = !preview" /><UButton label="Save question" icon="i-lucide-save" color="primary" @click="save" /></header><div class="quizground-formatbar"><button>A</button><button><strong>B</strong></button><button><em>I</em></button><button><u>U</u></button><button>S</button><button>x¹</button><button>x₂</button><button>Σ</button><button>f(x)</button><span></span><button @click="explanation = explanation ? '' : 'Jawaban ini benar karena ...'">💡 Add answer explanation</button></div><main class="quizground-canvas"><div class="quizground-card"><div class="quizground-type"><span>▣</span> Multiple Choice <span>⌄</span></div><div v-if="preview" class="quizground-question-preview"><h1>{{ question || 'Type question here' }}</h1><div class="quizground-preview-options"><button v-for="(option, index) in options.filter(Boolean)" :key="option" :class="{ selected: answered === index, correct: answered !== null && index === correctIndex }" @click="answered = index"><span>{{ String.fromCharCode(65 + index) }}</span>{{ option }}</button></div><p v-if="answered !== null" class="quizground-preview-feedback">{{ answered === correctIndex ? 'Correct answer' : 'Try again' }}</p></div><template v-else><textarea v-model="question" class="quizground-question-input" placeholder="Type question here" aria-label="Pertanyaan quiz"></textarea><div class="quizground-answer-grid"><label v-for="(_, index) in options" :key="index" class="quizground-answer" :class="`answer-${index}`"><button type="button" aria-label="Tandai jawaban benar" :class="{ selected: correctIndex === index }" @click="correctIndex = index">✓</button><input v-model="options[index]" :placeholder="`Type answer option ${index + 1} here`"><button type="button" aria-label="Hapus opsi" @click="options[index] = ''">⌫</button></label></div><label class="quizground-toggle"><input v-model="multiple" type="checkbox"> Multiple correct answers</label><label v-if="explanation" class="quizground-explanation">Answer explanation<textarea v-model="explanation"></textarea></label></template></div></main></div>
</template>
