<script setup lang="ts">
import { EditorContent, useEditor } from '@tiptap/vue-3'
import StarterKit from '@tiptap/starter-kit'
import Placeholder from '@tiptap/extension-placeholder'
import Image from '@tiptap/extension-image'
import { CourseCodeBlock } from './CourseCodeBlock'

const props = defineProps<{ modelValue: Record<string, unknown> | string | null }>()
const emit = defineEmits<{ 'update:modelValue': [value: Record<string, unknown>] }>()
const parseContent = (value: typeof props.modelValue) => { if (!value) return { type: 'doc', content: [{ type: 'paragraph' }] }; if (typeof value === 'object') return value; try { return JSON.parse(value) } catch { return { type: 'doc', content: [{ type: 'paragraph' }] } } }
const imageInput = ref<HTMLInputElement | null>(null)
const editor = useEditor({ extensions: [StarterKit.configure({ codeBlock: false }), CourseCodeBlock, Image, Placeholder.configure({ placeholder: 'Tulis materi course di sini...' })], content: parseContent(props.modelValue), onUpdate: ({ editor: instance }) => emit('update:modelValue', instance.getJSON() as Record<string, unknown>) })
async function uploadImage(event: Event) { const file = (event.target as HTMLInputElement).files?.[0]; if (!file || !editor.value) return; const body = new FormData(); body.append('image', file); try { const result = await $fetch<{ url: string }>('/api/admin/assets/image', { method: 'POST', body }); editor.value.chain().focus().setImage({ src: result.url, alt: file.name }).run() } finally { if (imageInput.value) imageInput.value.value = '' } }
watch([editor, () => props.modelValue], ([instance, value]) => { if (instance) { const content = parseContent(value); if (JSON.stringify(instance.getJSON()) !== JSON.stringify(content)) instance.commands.setContent(content, false) } }, { deep: true, immediate: true })
onBeforeUnmount(() => editor.value?.destroy())
</script>
<template>
  <div v-if="editor" class="rich-editor"><div class="rich-editor-toolbar"><button type="button" :class="{ active: editor.isActive('bold') }" @mousedown.prevent @click="editor.chain().focus().toggleBold().run()"><strong>B</strong></button><button type="button" :class="{ active: editor.isActive('italic') }" @mousedown.prevent @click="editor.chain().focus().toggleItalic().run()"><em>I</em></button><button type="button" :class="{ active: editor.isActive('heading', { level: 2 }) }" @mousedown.prevent @click="editor.chain().focus().toggleHeading({ level: 2 }).run()">H2</button><button type="button" :class="{ active: editor.isActive('heading', { level: 3 }) }" @mousedown.prevent @click="editor.chain().focus().toggleHeading({ level: 3 }).run()">H3</button><button type="button" :class="{ active: editor.isActive('bulletList') }" @mousedown.prevent @click="editor.chain().focus().toggleBulletList().run()">• List</button><button type="button" :class="{ active: editor.isActive('orderedList') }" @mousedown.prevent @click="editor.chain().focus().toggleOrderedList().run()">1. List</button><button type="button" :class="{ active: editor.isActive('blockquote') }" @mousedown.prevent @click="editor.chain().focus().toggleBlockquote().run()">Quote</button><button type="button" @mousedown.prevent @click="editor.chain().focus().setHorizontalRule().run()">Divider</button><button type="button" @mousedown.prevent @click="editor.chain().focus().setCourseCode().run()">Code Playground</button><button type="button" @mousedown.prevent @click="imageInput?.click()">Image</button><input ref="imageInput" class="sr-only" type="file" accept=".png,.jpg,.jpeg,.webp,.gif" @change="uploadImage"><span></span><button type="button" :disabled="!editor.can().undo()" @mousedown.prevent @click="editor.chain().focus().undo().run()">↶</button><button type="button" :disabled="!editor.can().redo()" @mousedown.prevent @click="editor.chain().focus().redo().run()">↷</button></div><EditorContent :editor="editor" class="rich-editor-content" /></div>
</template>
