<script setup lang="ts">
definePageMeta({ layout: 'dashboard' })
type User = { id: string; name: string; email: string; role: 'user' | 'admin'; created_at: string }
type Course = { id: string; title: string; description: string; learning_objectives: string; image: string; level: string; category: string; duration: string; uploaded_at: string }
const { user, loadUser } = useAuth(); const users = ref<User[]>([]); const courses = ref<Course[]>([]); const loading = ref(true); const errorMessage = ref(''); const editing = ref<Course | null>(null)
const form = reactive({ title: '', description: '', learningObjectives: '', image: '', level: 'beginner', category: '', duration: '', uploadedAt: new Date().toISOString().slice(0, 10) })
async function loadAdminData() { if (!await loadUser()) return navigateTo({ path: '/login', query: { redirect: '/admin' } }); if (user.value?.role !== 'admin') return navigateTo('/dashboard'); const [userResult, courseResult] = await Promise.all([$fetch<{ users: User[] }>('/api/admin/users'), $fetch<{ courses: Course[] }>('/api/admin/courses')]); users.value = userResult.users; courses.value = courseResult.courses; loading.value = false }
async function updateUser(item: User) { await $fetch(`/api/admin/users/${item.id}`, { method: 'PATCH', body: { name: item.name, role: item.role } }) }
async function deleteUser(id: string) { await $fetch(`/api/admin/users/${id}`, { method: 'DELETE' }); await loadAdminData() }
function editCourse(item: Course) { editing.value = item; Object.assign(form, { ...item, learningObjectives: item.learning_objectives, uploadedAt: item.uploaded_at }) }
function resetForm() { editing.value = null; Object.assign(form, { title: '', description: '', learningObjectives: '', image: '', level: 'beginner', category: '', duration: '', uploadedAt: new Date().toISOString().slice(0, 10) }) }
async function saveCourse() { errorMessage.value = ''; try { if (editing.value) await $fetch(`/api/admin/courses/${editing.value.id}`, { method: 'PUT', body: form }); else await $fetch('/api/admin/courses', { method: 'POST', body: form }); resetForm(); await loadAdminData() } catch (error: any) { errorMessage.value = error.data?.statusMessage || error.data?.message || 'Course gagal disimpan' } }
async function deleteCourse(id: string) { await $fetch(`/api/admin/courses/${id}`, { method: 'DELETE' }); await loadAdminData() }
onMounted(loadAdminData)
</script>
<template>
  <main class="dashboard-content"><div v-if="loading" class="dashboard-loading">Memuat panel admin...</div><template v-else><div class="dashboard-page-heading"><div><p class="dashboard-eyebrow">Administration</p><h1>Admin Panel</h1><p>Kelola user dan course platform.</p></div><button class="button-primary" @click="resetForm">+ Course Baru</button></div><p v-if="errorMessage" class="auth-error">{{ errorMessage }}</p><section class="dashboard-panel"><div class="dashboard-panel-heading"><div><h2>Manage User</h2><p>{{ users.length }} user terdaftar</p></div></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Nama</th><th>Email</th><th>Role</th><th>Aksi</th></tr></thead><tbody><tr v-for="item in users" :key="item.id"><td><input v-model="item.name" @change="updateUser(item)"></td><td>{{ item.email }}</td><td><select v-model="item.role" :disabled="item.id === user?.id" @change="updateUser(item)"><option value="user">User</option><option value="admin">Admin</option></select></td><td><button class="admin-delete" :disabled="item.id === user?.id" @click="deleteUser(item.id)">Hapus</button></td></tr></tbody></table></div></section><section class="dashboard-panel"><div class="dashboard-panel-heading"><div><h2>Manage Course</h2><p>{{ courses.length }} course tersedia</p></div></div><form class="course-form" @submit.prevent="saveCourse"><input v-model="form.title" placeholder="Judul course" required><input v-model="form.category" placeholder="Kategori" required><input v-model="form.duration" placeholder="Durasi" required><input v-model="form.image" placeholder="URL gambar" required><select v-model="form.level"><option value="beginner">Dasar</option><option value="intermediate">Menengah</option><option value="advanced">Sulit</option></select><input v-model="form.uploadedAt" type="date" required><textarea v-model="form.description" placeholder="Deskripsi" required></textarea><textarea v-model="form.learningObjectives" placeholder="Tujuan pembelajaran" required></textarea><div><button class="button-primary" type="submit">{{ editing ? 'Simpan Perubahan' : 'Tambah Course' }}</button><button v-if="editing" class="button-outline" type="button" @click="resetForm">Batal</button></div></form><div class="admin-course-list"><article v-for="item in courses" :key="item.id" class="admin-course-item"><div><strong>{{ item.title }}</strong><span>{{ item.category }} · {{ item.level }}</span></div><div><button class="admin-edit" @click="editCourse(item)">Edit</button><button class="admin-delete" @click="deleteCourse(item.id)">Hapus</button></div></article></div></section></template></main>
</template>
