<script setup lang="ts">
import { courses, levelNames } from '~/data/courses'
import heroIllustration from '~/assets/illustration-hero.svg'
import aboutIllustration from '~/assets/illustration-about.svg'
import { motion } from 'motion-v'
const search = ref('')
const level = ref('all')
const selected = ref<(typeof courses)[number] | null>(null)
const filteredCourses = computed(() => courses.filter(course => (level.value === 'all' || course.level === level.value) && course.title.toLowerCase().includes(search.value.toLowerCase())))
const truncate = (value: string) => value.length > 100 ? `${value.slice(0, 100).trim()}...` : value
const date = (value: string) => new Intl.DateTimeFormat('id-ID', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(value))
</script>
<template>
  <SiteNav />
  <main>
    <section id="beranda" class="hero"><motion.div class="motion-layer hero-motion-layer" :initial="{ opacity: 0, y: 24 }" :animate="{ opacity: 1, y: 0 }" :transition="{ duration: 0.7, ease: 'easeOut' }"><div class="container hero-grid"><div><p class="hero-label">✦ Coding Camp 2026</p><h1 class="hero-title">Membangun kemampuan coding</h1><p class="hero-description">Coding Camp melatih peserta berpikir logis, memecahkan masalah, dan bekerja terstruktur lewat praktik dan project nyata, bukan sekadar teori.</p><div class="hero-cta"><a href="#course" class="button-primary">Mulai Sekarang →</a><a href="#tentang" class="button-outline">Lihat Kurikulum</a></div></div><div class="hero-illustration"><img :src="heroIllustration" alt="Coding learning illustration"></div></div></motion.div></section><div class="hero-spacer" aria-hidden="true"></div>
    <section id="tentang" class="section-about"><motion.div class="motion-layer about-motion-layer" :initial="{ opacity: 0, y: 32 }" :whileInView="{ opacity: 1, y: 0 }" :viewport="{ once: true, amount: 0.2 }" :transition="{ duration: 0.7, ease: 'easeOut' }"><div class="container about-grid"><div class="about-illustration"><img :src="aboutIllustration" alt="CodingCamp curriculum team illustration"></div><div><p class="about-text">Coding Camp merupakan kegiatan pembelajaran dan pelatihan untuk membangun kemampuan peserta di bidang pemrograman. Selain konsep dasar, peserta dilatih berpikir logis, memecahkan masalah, bekerja terstruktur, serta menerapkan pengetahuan lewat praktik dan project nyata sebagai ruang belajar bersama yang aktif dan kolaboratif.</p><p class="about-source">Coding Camp</p></div></div></motion.div></section>
    <div class="tech-marquee" aria-label="Teknologi yang dipelajari"><div class="tech-marquee-track"><span v-for="item in [{ name: 'Node.js', icon: 'devicon-nodejs-plain' }, { name: 'MySQL', icon: 'devicon-mysql-plain' }, { name: 'Laravel', icon: 'devicon-laravel-plain' }, { name: 'JavaScript', icon: 'devicon-javascript-plain' }, { name: 'React', icon: 'devicon-react-original' }, { name: 'Git', icon: 'devicon-git-plain' }, { name: 'HTML5', icon: 'devicon-html5-plain' }, { name: 'CSS3', icon: 'devicon-css3-plain' }, { name: 'Node.js', icon: 'devicon-nodejs-plain' }, { name: 'MySQL', icon: 'devicon-mysql-plain' }]" :key="`${item.name}-${item.icon}`" class="tech-marquee-item"><i :class="[item.icon, 'colored']" aria-hidden="true"></i><span>{{ item.name }}</span></span></div></div>
    <section id="course" class="section-course"><motion.div class="motion-layer course-motion-layer" :initial="{ opacity: 0, y: 32 }" :whileInView="{ opacity: 1, y: 0 }" :viewport="{ once: true, amount: 0.15 }" :transition="{ duration: 0.7, ease: 'easeOut' }"><div class="container"><div class="course-title-wrap"><h2 class="course-title">Pilih Course Kamu</h2><p class="course-subtitle">Cari berdasarkan topik atau saring sesuai tingkat kemampuanmu</p></div><div class="course-layout"><aside class="filter-panel"><div class="search-box">⌕<input v-model="search" type="search" placeholder="Cari nama course..."></div><p class="filter-label">Tingkat Pembelajaran</p><label v-for="item in [['all','Semua Tingkat'],['beginner','Dasar'],['intermediate','Menengah'],['advanced','Sulit']]" :key="item[0]" class="radio-option"><input v-model="level" type="radio" name="level" :value="item[0]"><span>{{ item[1] }}</span></label><button class="reset-filter-button" @click="search = ''; level = 'all'">Reset Filter</button></aside><div class="course-card-grid"><article v-for="course in filteredCourses" :key="course.id" class="course-card"><img class="card-preview" :src="course.image" :alt="course.title"><div class="card-body"><div class="card-header-meta"><span class="card-category">{{ course.category }}</span><span class="card-duration">◷ {{ course.duration }}</span></div><h3 class="card-title">{{ course.title }}</h3><p class="card-description">{{ truncate(course.description) }}</p><div class="card-level-row"><span :class="['level-badge-inline', course.level]">{{ levelNames[course.level] }}</span><span class="card-date">{{ date(course.uploadedAt) }}</span></div><div class="card-actions"><button class="button-detail" @click="selected = course">Detail</button><NuxtLink :to="`/course/javascript_dasar?id=${course.id}`" class="button-start-learning">Mulai</NuxtLink></div></div></article><div v-if="!filteredCourses.length" class="empty-state"><p>Course tidak ditemukan</p><p>Coba ubah kata kunci atau filter tingkat</p></div></div></div></div></motion.div></section>
  </main>
  <div v-if="selected" class="detail-overlay" @click.self="selected = null"><div class="detail-panel"><button class="detail-panel-close" aria-label="Tutup detail" @click="selected = null">×</button><img class="detail-panel-image" :src="selected.image" :alt="selected.title"><p class="detail-panel-category">{{ selected.category }} · {{ selected.duration }}</p><h2 class="detail-panel-title">{{ selected.title }}</h2><p class="detail-panel-description">{{ selected.description }}</p><p class="detail-panel-section-label">Tujuan Pembelajaran</p><p class="detail-panel-description">{{ selected.learningObjectives }}</p><div class="detail-panel-footer"><span :class="['level-badge-inline', selected.level]">{{ levelNames[selected.level] }}</span><NuxtLink :to="`/course/javascript_dasar?id=${selected.id}`" class="button-start-learning">Mulai Belajar</NuxtLink></div></div></div>
</template>
