<script setup lang="ts">
definePageMeta({ layout: false })

const route = useRoute()
const validMenus = ['overview', 'course', 'assignment', 'progress', 'calender', 'settings']
if (!validMenus.includes(String(route.params.menu))) await navigateTo('/dashboard/overview')

import { courses as fallbackCourses, levelNames } from '~/data/courses'
import { courseSlug } from '~/utils/course-route'
const { user, loadUser } = useAuth()
const loading = ref(!user.value)
const search = ref('')
const courseProgress = 60
const courseQuery = ref('')
const courseLevel = ref('all')
const courseList = ref<any[]>(fallbackCourses)
const selectedCourse = ref<any>(null)
const mentors = [['AL', 'Abraham Kolin', 'Lead product designer @codingcamp'], ['JE', 'Julia Eve', 'Frontend mentor @codingcamp'], ['CL', 'Chester Lotus', 'Marketing mentor @codingcamp'], ['MR', 'Maxwell Reed', 'Full-stack developer @codingcamp'], ['SL', 'Sophie Lane', 'Design mentor @codingcamp'], ['OG', 'Oliver Grant', 'Project mentor @codingcamp']]
const filteredCourses = computed(() => courseList.value.filter(course => (courseLevel.value === 'all' || course.level === courseLevel.value) && course.title.toLowerCase().includes(courseQuery.value.toLowerCase())))

onMounted(async () => { if (!user.value && !await loadUser()) await navigateTo({ path: '/login', query: { redirect: '/dashboard/overview' } }); try { const result = await $fetch<{ courses: any[] }>('/api/courses'); if (result.courses.length) courseList.value = result.courses } catch {} loading.value = false })
async function logout() { await $fetch('/api/auth/logout', { method: 'POST' }); user.value = null; await navigateTo('/') }
async function learn(course: any) { await navigateTo(`/course/${courseSlug(course.title)}?id=${course.id}`) }
</script>

<template>
  <div v-if="loading" class="user-dashboard-loading">Memuat dashboard...</div>
  <div v-else-if="user" class="user-dashboard-shell">
    <StudentDashboardSidebar :logout="logout" />
    <main class="user-dashboard-main">
      <header class="user-dashboard-topbar"><div><h1>Welcome back <UIcon name="i-lucide-hand" /></h1><p>Let's learn something new today!</p></div><div class="user-dashboard-top-actions"><label class="user-dashboard-search"><UIcon name="i-lucide-search" /><input v-model="search" placeholder="Search" aria-label="Search"></label><button aria-label="Notifications"><UIcon name="i-lucide-bell" /></button><div class="user-dashboard-avatar">{{ user.name.slice(0, 2).toUpperCase() }}</div><div class="user-dashboard-profile-name"><strong>{{ user.name }}</strong><small>@{{ user.email.split('@')[0] }}</small></div></div></header>
      <section v-if="route.params.menu === 'course'" class="user-dashboard-course-page"><div class="user-dashboard-page-intro"><div><p class="user-dashboard-eyebrow">MY LEARNING</p><h2>Choose your course</h2><p>Temukan course yang ingin kamu pelajari dan lanjutkan progress-mu.</p></div><span class="user-dashboard-course-count">{{ filteredCourses.length }} course tersedia</span></div><div class="user-dashboard-course-toolbar"><label class="user-dashboard-course-search"><UIcon name="i-lucide-search" /><input v-model="courseQuery" placeholder="Cari course..." aria-label="Cari course"></label><select v-model="courseLevel" aria-label="Filter level"><option value="all">Semua level</option><option value="beginner">Dasar</option><option value="intermediate">Menengah</option><option value="advanced">Sulit</option></select></div><div class="user-dashboard-course-grid"><article v-for="course in filteredCourses" :key="course.id" class="user-dashboard-course-tile"><img :src="course.image" :alt="course.title"><div class="user-dashboard-course-tile-body"><div class="user-dashboard-course-meta"><span>{{ course.category }}</span><small><UIcon name="i-lucide-clock-3" /> {{ course.duration }}</small></div><h3>{{ course.title }}</h3><p>{{ course.description }}</p><div class="user-dashboard-course-tile-footer"><span class="user-dashboard-level-badge">{{ levelNames[course.level] }}</span><button class="user-dashboard-course-detail" @click="selectedCourse = course">Lihat detail</button></div></div></article><p v-if="!filteredCourses.length" class="user-dashboard-course-empty">Course tidak ditemukan. Coba ubah pencarian atau filter.</p></div><div v-if="selectedCourse" class="user-dashboard-course-modal" @click.self="selectedCourse = null"><article><button class="user-dashboard-modal-close" aria-label="Tutup detail" @click="selectedCourse = null"><UIcon name="i-lucide-x" /></button><img :src="selectedCourse.image" :alt="selectedCourse.title"><p class="user-dashboard-eyebrow">{{ selectedCourse.category }} · {{ selectedCourse.duration }}</p><h2>{{ selectedCourse.title }}</h2><p>{{ selectedCourse.description }}</p><p>{{ selectedCourse.learningObjectives }}</p><button class="user-dashboard-modal-action" @click="learn(selectedCourse)">Mulai belajar <UIcon name="i-lucide-arrow-right" /></button></article></div></section>
      <section v-else class="user-dashboard-layout">
        <div class="user-dashboard-primary"><section id="course-progress" class="user-dashboard-card user-dashboard-course-card"><div class="user-dashboard-card-heading"><div><h2>Dasar Pemrograman JavaScript</h2><p><span><UIcon name="i-lucide-clock-3" /></span> 1h 40m &nbsp; <span><UIcon name="i-lucide-layers-3" /></span> 8 chapter &nbsp; <span><UIcon name="i-lucide-circle-play" /></span> 7 videos</p></div><span class="user-dashboard-more"><UIcon name="i-lucide-ellipsis" /></span></div><div class="user-dashboard-progress-label"><span>Course complete</span><b>{{ courseProgress }}%</b></div><div class="user-dashboard-progress"><i :style="{ width: `${courseProgress}%` }"></i></div><NuxtLink to="/dashboard/course" class="user-dashboard-continue">Continue learning <UIcon name="i-lucide-play" /></NuxtLink></section><section class="user-dashboard-mini-grid"><article class="user-dashboard-card user-dashboard-mini-card"><div class="user-dashboard-card-heading"><h2>Progress</h2><small>Month⌄</small></div><strong>40 <small>hours</small></strong><p>Time spend</p><b>1 course</b><p>Completed</p><b>2 course</b><p>Enrolled</p></article><article class="user-dashboard-card user-dashboard-mini-card"><h2>Your Activity</h2><strong>17 <small>Days</small></strong><p>65 hours 20 minutes</p><div class="user-dashboard-dots"><i v-for="n in 21" :key="n" :class="{ muted: n > 17 }"></i></div></article></section><section id="study-statistics" class="user-dashboard-card user-dashboard-statistics"><div class="user-dashboard-card-heading"><h2>Study Statistics</h2><small>Weekly⌄</small></div><div class="user-dashboard-chart"><div class="user-dashboard-chart-y"><span v-for="label in ['8h', '7h', '5h', '3h', '1h', '0h']" :key="label">{{ label }}</span></div><div class="user-dashboard-bars"><div v-for="(height, index) in [48, 78, 39, 70, 52, 32, 76]" :key="index" class="user-dashboard-bar" :style="{ height: `${height}%` }"></div></div></div><div class="user-dashboard-chart-labels"><span v-for="day in ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']" :key="day">{{ day }}</span></div><div class="user-dashboard-legend"><span><i></i> Active</span><span><i></i> Goal</span></div></section></div>
        <div class="user-dashboard-secondary"><section class="user-dashboard-card user-dashboard-promo"><p class="user-dashboard-eyebrow">KEEP MOVING</p><h2>Keep learning new things everyday</h2><p>Get ready for an exciting journey into new knowledge! Explore lessons and grow your skills.</p><NuxtLink to="/dashboard/course" class="user-dashboard-community">Continue course <b><UIcon name="i-lucide-arrow-up-right" /></b></NuxtLink><div class="user-dashboard-promo-shape" aria-hidden="true"><UIcon name="i-lucide-sparkles" /></div></section><section class="user-dashboard-card user-dashboard-mentors"><div class="user-dashboard-card-heading"><h2>Top Mentors</h2><NuxtLink to="/#tentang">View all</NuxtLink></div><div v-for="mentor in mentors" :key="mentor[1]" class="user-dashboard-mentor"><span>{{ mentor[0] }}</span><b>{{ mentor[1] }}</b><small>{{ mentor[2] }}</small><i><UIcon name="i-lucide-ellipsis" /></i></div></section></div>
      </section>
    </main>
  </div>
</template>
